# Generated by Django 4.2.7 on 2023-11-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0002_followermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
