# Generated by Django 4.2.7 on 2023-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0003_userprofilemodel_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
